name: BLD

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      APP_NAME: "ms-openai"
      DOCKERFILE: ".ci/Dockerfile"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          context: .
          dockerfile: $DOCKERFILE
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/$APP_NAME
          push: true
          tags: ${{ github.sha }}, latest